apiVersion: v1
kind: Service
metadata:
  name: fiews-service
  namespace: kovan
spec:
  selector:
    app: fiews-failover
  ports:
    - protocol: TCP
      port: 4000
      targetPort: 4000