apiVersion: v1
kind: Service
metadata:
  name: chainlink-service
  namespace: "kovan"
spec:
  type: ClusterIP
  selector:
    app: kovan-node
  ports:
    - protocol: TCP
      port: 6689
      targetPort: 6689
